exclusively use if statements instead of &&/|| echo

diff --git a/dot_bin/executable_check-setup b/dot_bin/executable_check-setup
--- a/dot_bin/executable_check-setup
+++ b/dot_bin/executable_check-setup
@@ -91,7 +91,9 @@ expected_vars=(
 )
 set +u
 for var in "${expected_vars[@]}"; do
-  [[ -z "${!var}" ]] && echo "Environment variable not set: ${var}"
+  if [[ -z "${!var}" ]]; then
+    echo "Environment variable not set: ${var}"
+  fi
 done
 if [[ -n "${DESKTOP_OR_LAPTOP}" && "${DESKTOP_OR_LAPTOP}" != 'desktop' && "${DESKTOP_OR_LAPTOP}" != 'laptop' ]]; then
   echo "DESKTOP_OR_LAPTOP is not set to 'desktop' or 'laptop'"
@@ -199,17 +201,19 @@ path_remove "${HOME}/.bin"
 path_remove "${HOME}/.bin/other"
 
 for executable in "${expected_executables[@]}"; do
-  executable_exists "${executable}" > /dev/null 2>&1 || echo "Executable not available: ${executable}"
+  if ! executable_exists "${executable}" > /dev/null 2>&1; then
+    echo "Executable not available: ${executable}"
+  fi
 done
 
 ## check that the `trash` command is from trash-d and not trash-cli
-if executable_exists 'trash'; then
-  trash --version | contains_word 'trash-d' || echo "trash command is not from trash-d"
+if executable_exists 'trash' && ! trash --version | contains_word 'trash-d'; then
+  echo "trash command is not from trash-d"
 fi
 
 ## check that the `tldr` command is from tealdeer
-if executable_exists 'tldr'; then
-  tldr --version | contains_word 'tealdeer' || echo "tldr command is not from tealdeer"
+if executable_exists 'tldr' && ! tldr --version | contains_word 'tealdeer'; then
+  echo "tldr command is not from tealdeer"
 fi
 
 set +u
@@ -225,7 +229,9 @@ expected_files=(
   '/etc/fail2ban/jail.local'
 )
 for file in "${expected_files[@]}"; do
-  file_exists "${file}" || echo "Missing file: ${file}"
+  if ! file_exists "${file}"; then
+    echo "Missing file: ${file}"
+  fi
 done
 
 if ! is_headless; then
@@ -254,19 +260,20 @@ if ! is_headless; then
   if executable_exists 'fc-list'; then
     installed_fonts="$(fc-list : family)"
     for font in "${expected_fonts[@]}"; do
-      contains_word "${font}" <<< "${installed_fonts}" ||
-        contains_word "${font}TTF" <<< "${installed_fonts}" ||
-        contains_word "$(echo -e "${font}" | tr --delete '[:space:]')" <<< "${installed_fonts}" ||
-        contains_word "$(echo -e "${font}TTF" | tr --delete '[:space:]')" <<< "${installed_fonts}" ||
+      if ! contains_word "${font}" <<< "${installed_fonts}" &&
+        ! contains_word "${font}TTF" <<< "${installed_fonts}" &&
+        ! contains_word "$(echo -e "${font}" | tr --delete '[:space:]')" <<< "${installed_fonts}" &&
+        ! contains_word "$(echo -e "${font}TTF" | tr --delete '[:space:]')" <<< "${installed_fonts}"; then
         echo "Font not available: ${font}"
+      fi
     done
   else
     echo "No fc-list, skipping font checks"
   fi
 fi
 
-if executable_exists 'loginctl'; then
-  loginctl show-user "${USER}" --property=Linger | contains_word 'yes' || echo "${USER} is not set to linger"
+if executable_exists 'loginctl' && ! loginctl show-user "${USER}" --property=Linger | contains_word 'yes'; then
+  echo "${USER} is not set to linger"
 fi
 
 expected_active_system_services=('cups' 'fail2ban' 'sshd' 'ufw')
@@ -277,7 +284,9 @@ if is_personal && is_desktop; then
   expected_active_system_services+=('nfs-server')
 fi
 for service in "${expected_active_system_services[@]}"; do
-  systemctl is-active --quiet "${service}" || echo "System service not active: ${service}"
+  if ! systemctl is-active --quiet "${service}"; then
+    echo "System service not active: ${service}"
+  fi
 done
 
 expected_enabled_system_services=()
@@ -285,17 +294,23 @@ if is_personal && is_desktop; then
   expected_enabled_system_services+=('libvirtd')
 fi
 for service in "${expected_enabled_system_services[@]}"; do
-  systemctl is-enabled --quiet "${service}" || echo "System service not enabled: ${service}"
+  if ! systemctl is-enabled --quiet "${service}"; then
+    echo "System service not enabled: ${service}"
+  fi
 done
 
 expected_active_user_services=('autotrash.timer' 'journalctl-vacuum.timer' 'ssh-agent')
 for service in "${expected_active_user_services[@]}"; do
-  systemctl is-active --user --quiet "${service}" || echo "User service not active: ${service}"
+  if ! systemctl is-active --user --quiet "${service}"; then
+    echo "User service not active: ${service}"
+  fi
 done
 
 expected_enabled_user_services=()
 for service in "${expected_enabled_user_services[@]}"; do
-  systemctl is-enabled --user --quiet "${service}" || echo "User service not enabled: ${service}"
+  if ! systemctl is-enabled --user --quiet "${service}"; then
+    echo "User service not enabled: ${service}"
+  fi
 done
 
 expected_groups=('sys' 'wheel')
@@ -304,7 +319,9 @@ if is_personal && is_desktop; then
 fi
 actual_groups="$(groups "${USER}")"
 for group in "${expected_groups[@]}"; do
-  contains_word "${group}" <<< "${actual_groups}" || echo "User is not in group: ${group}"
+  if ! contains_word "${group}" <<< "${actual_groups}"; then
+    echo "User is not in group: ${group}"
+  fi
 done
 
 if ! is_headless; then
@@ -315,25 +332,31 @@ if ! is_headless; then
   )
   for kvals in "${expected_kvals[@]}"; do
     IFS=' ' read -r k v <<< "${kvals}"
-    [[ $(sysctl -n "${k}") -le "${v}" ]] || echo "Kernel variable ${k} is >${v}: $(sysctl -n "${k}")"
+    if [[ ! $(sysctl -n "${k}") -le "${v}" ]]; then
+      echo "Kernel variable ${k} is >${v}: $(sysctl -n "${k}")"
+    fi
   done
 fi
 
-if executable_exists 'rustup'; then
-  [[ "$(rustup toolchain list)" != stable* ]] && echo "rust toolchain is not 'stable'"
+if executable_exists 'rustup' && [[ "$(rustup toolchain list)" != stable* ]]; then
+  echo "rust toolchain is not 'stable'"
 fi
 
-[[ $(timedatectl show) != *'NTP=yes'* ]] && echo 'timedatectl set-ntp is not set'
+if [[ $(timedatectl show) != *'NTP=yes'* ]]; then
+  echo 'timedatectl set-ntp is not set'
+fi
 
-if executable_exists 'flatpak'; then
-  flatpak remotes | contains_word 'flathub' || echo 'Flathub flatpak repo is not installed'
+if executable_exists 'flatpak' && ! flatpak remotes | contains_word 'flathub'; then
+  echo 'Flathub flatpak repo is not installed'
 fi
 
 if is_distro 'fedora'; then
   expected_dnf_conf_vals=('max_parallel_downloads' 'defaultyes' 'keepcache')
   dnf_conf_text="$(cat '/etc/dnf/dnf.conf')"
   for dnf_conf_val in "${expected_dnf_conf_vals[@]}"; do
-    [[ -z $(grep --fixed-strings "${dnf_conf_val}" <<< "${dnf_conf_text}" | cut -d'=' -f2 | xargs) ]] && echo "dnf conf ${dnf_conf_val} is not set"
+    if [[ -z $(grep --fixed-strings "${dnf_conf_val}" <<< "${dnf_conf_text}" | cut -d'=' -f2 | xargs) ]]; then
+      echo "dnf conf ${dnf_conf_val} is not set"
+    fi
   done
   installed_packages="$(dnf list --installed | cut -d' ' -f1)"
   expected_rpm_fusions_packages=(
@@ -343,17 +366,25 @@ if is_distro 'fedora'; then
     'rpmfusion-nonfree-release'
   )
   for rpm_fusion_pacakge in "${expected_rpm_fusions_packages[@]}"; do
-    contains_word "${rpm_fusion_pacakge}" <<< "${installed_packages}" || echo "${rpm_fusion_pacakge} is not installed"
+    if ! contains_word "${rpm_fusion_pacakge}" <<< "${installed_packages}"; then
+      echo "${rpm_fusion_pacakge} is not installed"
+    fi
   done
 fi
 
 if executable_exists 'ufw'; then
   readonly ufw_status="$(sudo ufw status verbose)"
-  contains_word 'Status: active' <<< "${ufw_status}" || echo "UFW is not active"
-  contains_word 'deny (incoming)' <<< "${ufw_status}" || echo "UFW is not denying incoming by default"
-  contains_word 'allow (outgoing)' <<< "${ufw_status}" || echo "UFW is not allowing outgoing by default"
+  if ! contains_word 'Status: active' <<< "${ufw_status}"; then
+    echo "UFW is not active"
+  fi
+  if ! contains_word 'deny (incoming)' <<< "${ufw_status}"; then
+    echo "UFW is not denying incoming by default"
+  fi
+  if ! contains_word 'allow (outgoing)' <<< "${ufw_status}"; then
+    echo "UFW is not allowing outgoing by default"
+  fi
 fi
 
-if executable_exists 'aa-enabled'; then
-  aa-enabled | contains_word 'yes' || echo "AppArmor is not enabled"
+if executable_exists 'aa-enabled' && ! aa-enabled | contains_word 'yes'; then
+  echo "AppArmor is not enabled"
 fi
