bashrc updates after moving stuff to scripts repo

diff --git a/dot_config/bash/rc b/dot_config/bash/rc
--- a/dot_config/bash/rc
+++ b/dot_config/bash/rc
@@ -70,10 +70,22 @@ initial_shell_options="$-"
 initial_pipefail_option="$(grep --quiet --only-matching --fixed-strings 'pipefail' <<< "${SHELLOPTS}")"
 set -euo pipefail
 
-# this sets the XDG_* env vars
-if [[ -f "${HOME}/.profile" && -r "${HOME}/.profile" ]]; then
-  source "${HOME}/.profile"
-fi
+# functions used in my bash config files
+function __executable_exists() {
+  type -aPf "$1" > /dev/null 2>&1
+}
+function __is_readable_file() {
+  [[ -f "$1" && -r "$1" ]]
+}
+function __path_remove() {
+  PATH=$(echo -n "$PATH" | awk -v RS=: -v ORS=: '$0 != "'"$1"'"' | sed 's/:$//')
+}
+function __path_append() {
+  __path_remove "$1" && PATH="$PATH:$1"
+}
+function __path_prepend() {
+  __path_remove "$1" && PATH="$1:$PATH"
+}
 
 # Arch Box Sourcing
 # /etc/profile
@@ -83,13 +95,18 @@ fi
 #       /etc/bash_completion.d/*
 #       ~/.bash_completion
 
+# this sets the XDG_* env vars
+if __is_readable_file "${HOME}/.profile"; then
+  source "${HOME}/.profile"
+fi
+
 ## my files to source
 for file in \
   "${XDG_CONFIG_HOME}/bash/functions" \
   "${XDG_CONFIG_HOME}/bash/exports" \
   "${XDG_CONFIG_HOME}/bash/aliases" \
   "${XDG_CONFIG_HOME}/bash/local"; do
-  if [[ -f "${file}" && -r "${file}" ]]; then
+  if __is_readable_file "${file}"; then
     source "${file}"
   fi
 done
@@ -102,7 +119,7 @@ for file in \
   '/usr/share/doc/pkgfile/command-not-found.bash' \
   "${SDKMAN_DIR}/bin/sdkman-init.sh" \
   "${XDG_CONFIG_HOME}/broot/launcher/bash/br"; do
-  if is_readable_file "${file}"; then
+  if __is_readable_file "${file}"; then
     ## TODO look into addressing sdkman unbound variables
     set +u ## sdkman init references a bunch of unbound variables
     source "${file}"
@@ -112,20 +129,21 @@ done
 
 ## dirs to put on path
 for dir in \
-  "$(if executable_exists 'ruby'; then echo "$(ruby -e 'puts Gem.user_dir')/bin"; else echo ''; fi)" \
-  "$(if executable_exists 'go'; then echo "$(go env GOPATH)/bin"; else echo ''; fi)" \
+  "$(if __executable_exists 'ruby'; then echo "$(ruby -e 'puts Gem.user_dir')/bin"; else echo ''; fi)" \
+  "$(if __executable_exists 'go'; then echo "$(go env GOPATH)/bin"; else echo ''; fi)" \
   "$(if [[ -n "${CARGO_HOME}" ]]; then echo "${CARGO_HOME}/bin"; else echo ''; fi)" \
-  "${HOME}/.bin/other" \
-  "${HOME}/.bin"; do
+  "${HOME}/.local/bin" \
+  "${CODE_DIR}/scripts/main" \
+  "${CODE_DIR}/scripts/other"; do
   if [[ -n "${dir}" && -d "${dir}" ]]; then
-    path_prepend "${dir}"
+    __path_prepend "${dir}"
   fi
 done
 
 ## misc init stuff
-is_readable_file "${XDG_CONFIG_HOME}/dircolors" && eval "$(dircolors "${XDG_CONFIG_HOME}/dircolors")"
-executable_exists 'aws_completer' && complete -C 'aws_completer' aws
-executable_exists 'zoxide' && eval "$(zoxide init bash)"
+__is_readable_file "${XDG_CONFIG_HOME}/dircolors" && eval "$(dircolors "${XDG_CONFIG_HOME}/dircolors")"
+__executable_exists 'aws_completer' && complete -C 'aws_completer' aws
+__executable_exists 'zoxide' && eval "$(zoxide init bash)"
 
 # reset shell options to what they were initially
 set +euox pipefail
@@ -136,10 +154,11 @@ for shell_option in 'e' 'u' 'x'; do
 done
 [[ -n "${initial_pipefail_option}" ]] && set -o pipefail
 
-# clean up vars
-unset -v file dir shell_option initial_shell_options initial_pipefail_option
-
 ## TODO submit PR to address unbound variables?
 ## put this dead last as starship_preexec() will run before every command
 #STARSHIP_PREEXEC_READY=false
-executable_exists 'starship' && eval "$(starship init bash)"
+__executable_exists 'starship' && eval "$(starship init bash)"
+
+# clean up vars & functions
+unset -v file dir shell_option initial_shell_options initial_pipefail_option
+unset -f __executable_exists __is_readable_file __path_append __path_prepend __path_remove
